version: 2
general:
  artifacts:

do_steps: &do_steps
 steps:
  - run: echo "$CROSS_COMPILE" > ~/_cross_compile
  - restore_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}
  - run:
      name: checkout build tree
      command: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        if ! [ -d .git ]; then
          git clone --depth=1 $CIRCLE_REPOSITORY_URL .;
        fi
        if [[ $CIRCLE_BRANCH == pull/* ]]; then
           git fetch --depth=1 origin $CIRCLE_BRANCH/head;
        else
           git fetch --depth=1 origin $CIRCLE_BRANCH;
        fi
        git reset --hard $CIRCLE_SHA1
  - save_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}-{{ epoch }}
      paths:
        - /home/ubuntu/project/.git
  - run:
      name: clean
      command: |
        make mrproper
        cd tools/lkl && make clean-conf
        rm -rf ~/junit
  - run: mkdir -p /home/ubuntu/.ccache
  - restore_cache:
      key: compiler-cache-{{ checksum "~/_cross_compile" }}-{{ .Environment.CACHE_VERSION }}
  - run:
      name: copy mingw binutils
      command: |
        if [ "$CROSS_COMPILE" = "i686-w64-mingw32-" ]; then
          wget https://github.com/lkl/linux/raw/master/tools/lkl/bin/i686-w64-mingw32-as
          wget https://github.com/lkl/linux/raw/master/tools/lkl/bin/i686-w64-mingw32-ld
          wget https://github.com/lkl/linux/raw/master/tools/lkl/bin/i686-w64-mingw32-objcopy
          sudo cp i686-w64-mingw32-* /usr/bin;
        elif [ "$CROSS_COMPILE" = "arm-linux-androideabi-" ]; then
          wget https://github.com/lkl/linux/raw/master/tools/lkl/bin/arm-linux-androideabi-ld.gold
          sudo cp arm-linux-androideabi-ld.gold /usr/bin/arm-linux-androideabi-ld;
        fi
  - run:
      name: start emulator
      command: |
        if [[ $CROSS_COMPILE == *android* ]]; then
          emulator -avd Nexus5_API24 -no-window -no-audio -no-boot-anim;
        fi
      background: true
  - run: cd tools/lkl && make -j8 ${MKARG}
  - run: mkdir -p ~/destdir && cd tools/lkl && make DESTDIR=~/destdir
  - save_cache:
     paths:
       - /home/ubuntu/.ccache
     key: compiler-cache-{{ checksum "~/_cross_compile" }}-{{ .Environment.CACHE_VERSION }}-{{ epoch }}
  - run:
      name: wait emulator to boot
      command: |
        if [[ $CROSS_COMPILE == *android* ]]; then
          /home/ubuntu/circle-android.sh wait-for-boot;
        fi
  - run:
      name: run tests
      command: |
        sudo apt-get update
        sudo apt-get install -y slirp
        mkdir -p ~/junit
        make -C tools/lkl run-tests tests="--junit-dir ~/junit"
      no_output_timeout: "90m"
  - run:
      name: collecting test results
      command: |
        find ./tools/lkl/ -type f -name "*.xml" -exec mv {} ~/junit/ \;
  - store_test_results:
      path: ~/junit
  - store_artifacts:
      path: ~/junit


do_uml_steps: &do_uml_steps
 steps:
  - run: echo "$CROSS_COMPILE" > ~/_cross_compile
  - restore_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}
  - run:
      name: checkout build tree
      command: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        if ! [ -d .git ]; then
          git clone --depth=1 $CIRCLE_REPOSITORY_URL .;
        fi
        if [[ $CIRCLE_BRANCH == pull/* ]]; then
           git fetch --depth=1 origin $CIRCLE_BRANCH/head;
        else
           git fetch --depth=1 origin $CIRCLE_BRANCH;
        fi
        git reset --hard $CIRCLE_SHA1
  - save_cache:
      key: code-tree-shallow-{{ .Environment.CACHE_VERSION }}-{{ epoch }}
      paths:
        - /home/ubuntu/project/.git
  - run: mkdir -p /home/ubuntu/.ccache
  - restore_cache:
      key: compiler-cache-{{ checksum "~/_cross_compile" }}-{{ .Environment.CACHE_VERSION }}
  - run:
      name: build
      command: |
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib
        make defconfig ARCH=um SUBARCH=$SUBARCH
        make ARCH=um SUBARCH=$SUBARCH
  - save_cache:
     paths:
       - /home/ubuntu/.ccache
     key: compiler-cache-{{ checksum "~/_cross_compile" }}-{{ .Environment.CACHE_VERSION }}-{{ epoch }}
  - run:
      name: test
      command: |
        # XXX: i386 build doesn't work with the test
        if [ $CIRCLE_STAGE = "i386_uml" ] || [ $CIRCLE_STAGE = "i386_uml_on_x86_64" ]; then
          exit 0
        fi
        ./linux rootfstype=hostfs ro mem=1g loglevel=10 init="/bin/bash -c exit" || export RETVAL=$?
        # SIGABRT=6 => 128+6
        if [ $RETVAL != "134" ]; then
          exit 1
        fi

## Customize the test machine
jobs:
  x86_64:
   docker:
     - image: lkldocker/circleci-x86_64:0.7
   environment:
     CROSS_COMPILE: ""
   <<: *do_steps

  i386:
   docker:
     - image: lkldocker/circleci-i386:0.1
   environment:
     CROSS_COMPILE: ""
   <<: *do_steps

  mingw32:
   docker:
     - image: lkldocker/circleci-mingw:0.6
   environment:
     CROSS_COMPILE: "i686-w64-mingw32-"
   <<: *do_steps

  android-arm32:
   docker:
     - image: lkldocker/circleci-android-arm32:0.6
   environment:
     CROSS_COMPILE: "arm-linux-androideabi-"
     LKL_ANDROID_TEST: 1
     ANDROID_SDK_ROOT: /home/ubuntu/android-sdk
   <<: *do_steps

  android-aarch64:
   docker:
     - image: lkldocker/circleci-android-arm64:0.6
   environment:
     CROSS_COMPILE: "aarch64-linux-android-"
     LKL_ANDROID_TEST: 1
     ANDROID_SDK_ROOT: /home/ubuntu/android-sdk
   <<: *do_steps

  x86_64_valgrind:
   docker:
     - image: lkldocker/circleci-x86_64:0.7
   environment:
     CROSS_COMPILE: ""
     VALGRIND: 1
   <<: *do_steps

  x86_64_uml:
   docker:
     - image: lkldocker/circleci-x86_64:0.7
   environment:
     CROSS_COMPILE: ""
     TMPDIR: "/tmp" # required for not using /dev/shm
     SUBARCH: "x86_64"
   <<: *do_uml_steps

  i386_uml:
   docker:
     - image: lkldocker/circleci-i386:0.1
   environment:
     CROSS_COMPILE: ""
     SUBARCH: "i386"
     TMPDIR: "/tmp" # required for not using /dev/shm
   <<: *do_uml_steps

  i386_uml_on_x86_64:
   docker:
     - image: lkldocker/circleci-x86_64:0.7
   environment:
     CROSS_COMPILE: ""
     TMPDIR: "/tmp" # required for not using /dev/shm
     SUBARCH: "i386"
   <<: *do_uml_steps

  checkpatch:
   docker:
     - image: lkldocker/circleci:0.5
   environment:
   steps:
     - restore_cache:
        key: code-tree-full-history-{{ .Environment.CACHE_VERSION }}
     - checkout
     - run: sudo pip install ply
     - run: tools/lkl/scripts/checkpatch.sh
     - save_cache:
        key: code-tree-full-history-{{ .Environment.CACHE_VERSION }}-{{ epoch }}
        paths:
          - /home/ubuntu/project/.git
        when: always

workflows:
  version: 2
  build:
    jobs:
     - x86_64
     - x86_64_valgrind
     - mingw32
     - android-arm32
     - android-aarch64
     - checkpatch
     - i386
     - x86_64_uml
     - i386_uml
     - i386_uml_on_x86_64
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - x86_64_valgrind
